version: '3.9'

services:
  database:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/
    env_file:
      - config_files/database.env
    networks:
      hv_cao_network:

  hvcao_nuxt_docker:
    build:
      context: .
      dockerfile: Nuxt3Dockerfile
    ports:
      - '3099:3000'
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - hv_cao_network
      - npm-nw

  hvcao_api_docker:
    build:
      context: ./api
      dockerfile: ApiDjangoDockerfile
    command: bash -c "python manage.py migrate && gunicorn hvcao_rest_api.wsgi:application --bind 0.0.0.0:8002"
    volumes:
      - hvcao_static_volume:/code/django_static
      - hv_cao_media_volume:/code/django_mediafiles
    expose:
      - 8002
    env_file:
      - config_files/env.ssl
    restart: unless-stopped
    working_dir: /code  # Set the working directory to '/code'
    networks:
      - hv_cao_network
      - npm-nw
    depends_on:
      - database

networks:
  hv_cao_network:
  npm-nw:
    external: true


volumes:
  hvcao_static_volume:
  hv_cao_media_volume:
