version: '3.9'

services:
  hvcao_nuxt_docker:
    build:
      context: .
      dockerfile: Nuxt3Dockerfile
    command: npm run dev
    ports:
      - '3099:3000'
    environment:
      - NODE_ENV=production
    restart: always

  hvcao_api_docker:
    build:
      context: ./api
      dockerfile: ApiDjangoDockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver "
    volumes:
      - hvcao_static_volume:/code/django_static
      - hv_cao_media_volume:/code/django_mediafiles
    expose:
      - 8002
    env_file:
      - config_files/env.dev
    restart: unless-stopped
    working_dir: /code  # Set the working directory to '/code'




volumes:
  hvcao_static_volume:
  hv_cao_media_volume:
