# Generated by Django 4.1.10 on 2023-08-14 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question_manager', '0003_questionversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiondata',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_by_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questiondata',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
